events {}

http {

    upstream backend_pool {
        server backend-container-1:3000;
        server backend-container-2:3000;
    }

    server {
        listen 80;
        server_name localhost;

        add_header X-Served-By $upstream_addr always;

        location / {
            proxy_pass http://frontend-container:80;
        }

        location /api/ {
            proxy_pass http://backend_pool/;
        }
    }
}
